### ISSUE TITLE
Options not defined for M.Sidenav.init

### ISSUE THREAD

**Issue by jmckenney** [MaxHsieh0615/pigs-with-money#16]
https://github.com/bb19930615/pigs-with-money/blob/a09892b2b9e039afe9e2a43a08266f67863451f0/client/public/index.html#L50

```javascript
    document.addEventListener('DOMContentLoaded', function () {
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems, options);
    });
```

Take a look at options

**Comment by MaxHsieh0615** [comment]
Resolved with deleting these lines since we can just use the jQuery commands starting on line 59
